spring:
  liquibase:
    change-log: classpath:db/changelog/master.xml
  messages:
    basename: messages/messages
    encoding: UTF-8
    fallback-to-system-locale: false

  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    hikari:
      connection-timeout: ${MAX_CONNECTION_TIMEOUT}
      maximum-pool-size: ${MAX_POOL_SIZE}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true

  security:
    custom:
      jwt-secret: ${JWT_SECRET_KEY}
      jwt-expiration-in-ms: ${JWT_EXPIRATION_IN_MS}
    user:
      name: ${SECURITY_USER_NAME}
      password: ${SECURITY_USER_PASSWORD}
      roles: ${SECURITY_USER_ROLES}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE}

  servlet:
    multipart:
      enabled: true
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}

springdoc:
  pathsToMatch: /v1/api/**

app:
  file:
    storage:
      root: ${FILE_STORAGE_ROOT}
      quota-bytes: ${FILE_STORAGE_QUOTA_BYTES}
      video-chunk-size-bytes: ${FILE_STORAGE_VIDEO_CHUNK_SIZE_BYTES}
      max-video-size-bytes: ${FILE_STORAGE_MAX_VIDEO_SIZE_BYTES}
      max-size-bytes: ${FILE_STORAGE_MAX_SIZE_BYTES}
    server:
      url: http://localhost:8080/v1/api/files/

telegram:
  api-id: ${TELEGRAM_API_ID}
  api-hash: ${TELEGRAM_API_HASH}
  phone-number: ${TELEGRAM_PHONE_NUMBER}
  session-name: ${TELEGRAM_SESSION_NAME}
  session-path: ${TELEGRAM_SESSION_PATH}
